version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: tourplanner-db
    environment:
      POSTGRES_USER: Tom
      POSTGRES_PASSWORD: isteinHund
      POSTGRES_DB: tourplanner_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
