# Variables, to be used in all requests, like the API_KEY:
@apikey=5b3ce3597851110001cf6248ddb3f2dbe7c64e449fbb37f279af4f4d

### GeoCode-Search FHTW
@address1=Höchstädtplatz%206%201200%20Wien

GET https://api.openrouteservice.org/geocode/search?api_key={{apikey}}&text={{address1}}

@startat=16.377631,48.239223


### Directions from FHTW to Zanoni
@routeType=driving-car

GET https://api.openrouteservice.org/v2/directions/{{routeType}}?api_key={{apikey}}&start=16.377631,48.239223&end=16.372924,48.209379
